### ISSUE TITLE
The binary fails to run (missing dll)

### ISSUE THREAD

**Issue by fdb** [Gekkio/lcdoff-rs#2]
Trying to run the binary linked to in the README ([this one](http://gekkio.fi/files/lcdoff-rs/lcdoff-rs.exe)) fails because it's missing the `libgcc_s_dw2-1.dll` file.

**Comment by Gekkio** [comment]
Looks like some dependency implicitly required that DLL earlier, but that's no longer the case. I've refreshed the binary, and it should now work fine without extra DLLs.
